### ISSUE TITLE
你好 数据集能分享下不，没捞着报名，谢谢

### ISSUE THREAD

**Issue by BackT0TheFuture** [HighingLIN/NAIC-Person-Re-identification#1]

**Comment by HighingLIN** [comment]
文件很大的 超过5G




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HighingLIN/NAIC-Person-Re-identification"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 下午5:18
收件人:&nbsp;"HighingLIN/NAIC-Person-Re-identification"<NAIC-Person-Re-identification@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HighingLIN/NAIC-Person-Re-identification] 你好 数据集能分享下不，没捞着报名，谢谢 (#1)

**Comment by BackT0TheFuture** [comment]
如果方便的话可以传个网盘什么的，如果不方便那就算了
总之，非常感谢回复！
